---
- block:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove unnecessary packages and dependencies
      apt:
        autoremove: yes

    - name: Clean up the local repository of retrieved package files
      apt:
        autoclean: yes

    # - name: Reboot the server if required
    #   reboot:
    #     when: ansible_facts['pkg_mgr_reboot_required'] | default(false)
  tags: update
