---
- block:
  - name: Installing Spotify app
    become: true

  - name: Install Spotify Key
    become: true
    apt_key:
      url: 'https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg'
      state: present

  - name: Install Spotify Repository
    become: true
    apt_repository:
      repo: 'deb http://repository.spotify.com stable non-free'
      state: present
      filename: spotify

  - name: Install Spotify
    become: true
    apt:
      name: spotify-client
      update_cache: true
      state: present

  tags: spotify